### ISSUE TITLE
ライブラリと例外処理　Lv2 Q7, Q8

### ISSUE THREAD

**Issue by haruki869** [gishi-yama/contents#33]
選択肢に「例外ハンドラ」がでてくるが、ヒントには存在しない。「実行時例外」を選択肢にする？

--
選択肢
検査例外
非検査例外
例外ハンドラ

ヒント1
コンパイルする段階で起こりうることが想定され、例外処理を備えておくほうがよい例外を検査例外という。

ヒント2
プログラムを実行した際に状況によっては起こるかも知れず、必ずしも例外処理を備えなくてもよい例外を非検査例外という。

ヒント3
非検査例外は、実行時例外とも呼び、RuntimeExceptionとそのサブクラスで種類が表される。

**Comment by gishi-yama** [comment]
非検査例外＝実行時例外 なので、選択肢は変えず、ヒントを変える
