### ISSUE TITLE
クラス設計　Lv3 Q1

### ISSUE THREAD

**Issue by cist-b214-h-takahashi** [gishi-yama/contents#35]
```
以下の指示に従い、下のクラスをカプセル化しなさい。

全てのフィールド変数はクラス外部全てに公開する
全てのメソッドはクラス外部全てに公開する
```
となっていますが全てpublicの場合カプセル化と言って良いのでしょうか？
今後カプセル化をするという課題が出た場合全てpublicの人が出てくる可能性がありそうだなと思いました

**Comment by gishi-yama** [comment]
カプセル化は、フィールド隠蔽が良く例に挙げられますし王道ですが、イコールではなく、なんらかの指針に基づいて適切にアクセス範囲を設定することがカプセル化です。なので、全てpublicの場合も(実用的な意味があるかどうかは別として)カプセル化と言って差し支えはありません

また、その後の問題にはフィールド隠蔽のものも入っているので、誤解は防げるかなと思います。
この問題は一旦このまま作成でお願いします。
