### ISSUE TITLE
データモデルとDBMS Lv5 Q10

### ISSUE THREAD

**Issue by k-has9532** [gishi-yama/contents#39]
ヒント3がLv6の1のヒントではないかとの指摘
【 a 】になっている→他の問題と同じように【1】にすべきではとの指摘
ドロップボックスなのに選択肢も問題文に記述→問題文には記述がいらないのではないかとの指摘

以上、3点が指摘点です

**Comment by gishi-yama** [comment]
@k-has9532 

- ヒント3がLv6の1のヒントではないかとの指摘
  - Lv5Q10のヒント3は、原稿もeラーニング上も内容は正しいため、修正不要。（指摘箇所の勘違い？）
- 【 a 】になっている→他の問題と同じように【1】にすべきではとの指摘
  - a, b, cは元の問題からの引用のため、修正不要です。
- ドロップボックスなのに選択肢も問題文に記述→問題文には記述がいらないのではないかとの指摘
  - [もともと、原稿では指摘の通りになっています](https://github.com/gishi-yama/contents/blob/master/%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9/%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E3%81%AE%E8%A8%AD%E8%A8%88/%E3%83%87%E3%83%BC%E3%82%BF%E3%83%A2%E3%83%87%E3%83%AA%E3%83%B3%E3%82%B0/lv5.md#q10ドロップボックス)。作成者がア〜エをつけてしまったと思われるので、原稿にあわせて修正してください。
 
また追加で、ヒント3の改行がeラーニング上はおかしいので、修正してください。

**Comment by gishi-yama** [comment]
見る問題間違えてた

**Comment by gishi-yama** [comment]
@k-has9532 

- ヒント3がLv6の1のヒントではないかとの指摘
  - 原稿を修正しましたので、ヒント3を書き換えて下さい。
-【 a 】になっている→他の問題と同じように【1】にすべきではとの指摘
  - 過去問から引用しているため、このままで良いです。
- ドロップボックスなのに選択肢も問題文に記述→問題文には記述がいらないのではないかとの指摘
  - 原稿制作者が誤ってつけてしまったようなので、eラーニング上の表記から削除してください。
